version: "3"

services:
  
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: "host"
    restart: always
    ports:
      - 32400:32400
    environment:
      - VERSION=latest 
      - PUID=1001 
      - PGID=1001
      - TZ=${TIME_ZONE}
    volumes:
      - ${SERVER_PATH}/MediaServer/plex/config:/config:shared  
      - ${SERVER_PATH}/MediaServer/tvshows:/data/tvshows:shared  
      - ${SERVER_PATH}/MediaServer/movies:/data/movies:shared  
      - ${SERVER_PATH}/MediaServer/plex/transcode:/transcode:shared
    env_file: .env

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: "host"
    restart: always
    ports:
      - 8989:8989
    environment:
      - PUID=1001 
      - PGID=1001
      - TZ=${TIME_ZONE}
    volumes: 
      - ${SERVER_PATH}/MediaServer/sonarr/config:/config:shared 
      - ${SERVER_PATH}/MediaServer/tvshows:/tvshows:shared 
      - ${SERVER_PATH}/MediaServer/deluge/downloads:/downloads:shared
    env_file: .env

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: "host"
    restart: always
    ports:
      - 7878:7878
    environment:
      - PUID=1001 
      - PGID=1001
      - TZ=${TIME_ZONE}
    volumes: 
      - ${SERVER_PATH}/MediaServer/radarr/config:/config:shared 
      - ${SERVER_PATH}/MediaServer/movies:/movies:shared 
      - ${SERVER_PATH}/MediaServer/deluge/downloads:/downloads:shared 
      - /etc/localtime:/etc/localtime:ro 
    env_file: .env

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: "host"
    restart: always
    ports:
      - 8112:8112
    environment:
      - PUID=1001 
      - PGID=1001
      - TZ=${TIME_ZONE}
      - UMASK_SET=022 
    volumes: 
      - ${SERVER_PATH}/MediaServer/deluge/downloads:/downloads:shared  
      - ${SERVER_PATH}/MediaServer/deluge/config:/config:shared  
    env_file: .env
